config/routes.rb
TheProductivenator::Application.routes.draw do
  resources :users
  resources :tasks 
  resources :sessions, only: [:new, :create, :destroy]
  

  root to: 'static_pages#home'

  match '/signup',   to: 'users#new'
  match '/signin',   to: 'sessions#new'
  match '/signout',  to: 'sessions#destroy', via: :delete

  match '/home',    to: 'static_pages#home'

end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id         :integer          not null, primary key
#  task       :string(255)
#  task_etc   :integer
#  reward     :string(255)
#  reward_etc :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Task < ActiveRecord::Base
  attr_accessible :task, :task_etc, :reward, :reward_etc
  belongs_to :user
  
  validates :task, presence: true, length: { maximum: 140 }
  validates :task_etc, presence: true
  validates :reward, presence: true, length: { maximum: 140 }
  validates :reward_etc, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible  :name, :email, :password, :password_confirmation
  has_secure_password
  has_many :tasks, dependent: :destroy

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
  					format: { with: VALID_EMAIL_REGEX }, 
  					uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true				
 
  def todo_list
    Task.where("user_id = ?", id)
  end
  
  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	 def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or root_url 
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

	def destroy
		sign_out
		redirect_to root_url
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	if signed_in?
  	@task = current_user.tasks.build 
  	@todo_items = current_user.todo_list.all
  	end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :signed_in_user, only: [:create, :destroy]
  before_filter :correct_user,   only: :destroy


 	def create
 		@task = current_user.tasks.build(params[:task])
 		if @task.save
      flash[:success] = "Item added to your to-do list!"
 			redirect_to root_url
 		else
      @todo_items = []
      render 'static_pages/home'
 		end
 	end

  def destroy
    @task.destroy
    redirect_to root_url
  end

  private

      def correct_user
        @task = current_user.tasks.find_by_id(params[:id])
        redirect_to root_url if @task.nil?
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :signed_in_user, only: [:index, :edit, :update, :destroy]
	before_filter :correct_user,   only: [:edit, :update] 
  before_filter :admin_user,     only: [:index, :destroy]
 

	def new
  	@user = User.new
  end

	def create
		@user = User.new(params[:user])
		if @user.save 
			sign_in @user
			flash[:success] = "Welcome to The Productivenator!"
			redirect_to root_url 
		else
			render 'new'
		end
	end

	def edit
	end

	def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to root_url 
    else
      render 'edit'
    end
  end

  def index
    @users = User.paginate(page: params[:page])
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end

  
  private


    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "The Productivenator"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

# CODE TO IMPLEMENT FRIENDLY FORWARDING
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <small>A web application by Lushi Li</small>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "the productivenator", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
  	<div class="container">
       <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    	<%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_signup_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_task_form.html.erb
<h2 class="left-align">Add a new item</h2>
<div class="row">
<%= form_for(@task) do |f| %>

    <%= render 'shared/error_messages', object: f.object %>
    
    <div class="span3">
    <%= f.label :task, "Task" %>
    <%= f.text_field :task, placeholder: "Enter your task here" %>

    <%= f.label :task_etc, "for" %>
    <%= f.text_field :task_etc, placeholder: "approximate time to complete" %> minutes.
  	</div>

  	<div class="span3 offset1">
    <%= f.label :reward, "Reward" %>
    <%= f.text_field :reward, placeholder: "Enter a fun activity" %>

    <%= f.label :reward_etc, "for" %>
    <%= f.text_field :reward_etc, placeholder: "time allotted" %> minutes.
  	</div>
    <%= f.submit "Add to to-do list", class: "btn btn-small" %>
<% end %>
 </div>

app/views/shared/_tasks_error_messages.html.erb
<% if @task.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@task.errors.count, "error") %>.
    </div>
    <ul>
    <% @task.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_todo_item.html.erb
<li id="<%= todo_item.id %>">
<div class="task_item">
  <span class="task"><%= todo_item.task %></span>
  <span class="task_etc">for <%= pluralize(todo_item.task_etc, "minute") %>.</span>
 </div>
 <div class="reward_item">
  Your reward: <span class="reward"><%= todo_item.reward %></span>
  <span class="reward_etc">for <%= pluralize(todo_item.reward_etc, "minute") %>!</span>
 </div>
  <% if current_user?(todo_item.user) %>
    <%= link_to "Done", todo_item, method: :delete,
                                     data: { confirm: "Great job! Hope you enjoyed the reward. This item will be deleted." },
                                     title: todo_item.task %>
  <% end %>
</li>

app/views/shared/_todo_list.html.erb
<h1>My To-Do List</h1>
<% if @todo_items.any? %>
  <ol class="tasks">
    <%= render partial: 'shared/todo_item', collection: @todo_items %>
  </ol>

  <h5>Total:</h5>
  <p><%= pluralize(current_user.tasks.count, "task")%> left to do </p>
  
<% end %>

app/views/shared/_users_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About</h1>
<p>The Productivenator is a tool to help you keep track of your tasks... and reward yourself with the fun things you want to do! </p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact Us') %>
<h1>Contact</h1>
<p> This is the contact page of The Productivenator application. Questions? Comments? Suggestions? We would love to hear from you!</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>This is the help page of The Productivenator application</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
 <div class="row">
 	<div class="span8 offset2">
    	<section>
        <%= render 'shared/todo_list' %>
      </section>
      <br>
      <br>
      <section>
        <%= render 'shared/task_form' %>
      </section>
  </div> 
  </div> 
<% else %>

<div class="center hero-unit">
	<h1>The Productivenator</h1>
	
	<h2>
		A task manager to turn procrastination into productivity.
	</h2>

		<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

<% end %>

app/views/tasks/index.html.erb
<h1 class="center">What do you need to do today?</h1>

  <div>
    <%= form_for(@task) do |f| %>
      <%= render 'shared/tasks_error_messages' %>

      <%= f.label :task %>
      <%= f.text_field :task %>

      <%= f.label :task_etc, "for approximately" %>
      <%= f.text_field :task_etc %> minutes

      <%= f.label :reward, "Reward for completing task" %>
      <%= f.text_field :reward %>

      <%= f.label :reward_etc, "for" %>
      <%= f.text_field :reward_etc %> minutes

      <%= f.submit "Add to to-do list", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= link_to "See my to-do list", tasks_path, class: "btn btn-large btn-primary" %>
</div>


<% provide(:title, 'To-Do List for Today') %>
<h1>To-Do List for Today</h1>

<%= table_for @tasks do -%>
  <% columns :task, :task_etc, :reward, :reward_etc %>
<% end %>

<br>
<br>




<%= link_to "Add another item", create_path %>

app/views/tasks/new.html.erb
<% provide(:title, 'Create Your To-Do List') %>
<h1>Create Your To-Do List</h1>
<form>
	<label> 1.
		<input type="text" name="q">
	</label>
	<label> for
		<input type="hour" name="r">
	</label>
	<label> hour(s)
	</label>
</form>

app/views/tasks/show.html.erb
<ol class="tasks">
  <% @tasks.each do |task| %>
    <li>
      <%= task.task %>
      <%= task.task_etc %>
      <%= task.reward %>
      <%= task.reward_etc %>
    </li>
  <% end %>
</ol>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %> 
<h1>Edit your account</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= user.name %>
      <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
    	<%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
      <br><br>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<!--DELETE?-->

<% provide(:title, @user.name) %>
<h1>
	Your To-Do List
</h1>
    <% if @user.tasks.any? %> 
      <h3>Tasks (<%= @user.tasks.count %>)</h3>
      <ol class="tasks">
        <%= render @tasks %>
      </ol>
      <%= will_paginate @tasks %>
    <% end %>
 